// Generated by https://quicktype.io

export const isKeyboardFrameT = (frame: any): frame is KeyboardFrameT => {
  return frame.endCoordinates !== undefined;
};

export interface KeyboardFrameT extends Object {
  duration: number;
  easing: string;
  endCoordinates: Coordinates;
  isEventFromThisApp: boolean;
  startCoordinates: Coordinates;
}

export interface Coordinates {
  height: number;
  screenX: number;
  screenY: number;
  width: number;
}
